#!/usr/bin/env bash
# An Nginx webserver configuration script

apt-get -y update
apt-get -y install nginx
mkdir -p /var/www/html
touch /var/www/html/index.html
echo 'Hello World!' > /var/www/html/index.html
service nginx restart
