#!/usr/bin/env bash
# redirecting the redirect_me path


printf %s "server {
    listen 80 default_server;
    listen  [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm;
    if(\$redirect_filename ~ redirect_me) {
          return 301;
    }
}    
" > /etc/nginx/sites-available/default

#starting the server
if [ "pgrep -c nginx" -lt 0]
    then
    service nginx start
    else
    service nginx restart
fi
