#!/usr/bin/env bash
# redirecting the redirect_me path


printf %s "server {
    listen 80 default_server;
    listen  [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm;
    location /redirect_me {
          return 301
    }
}    
" > /etc/nginx/sites-available/default

service nginx restart
