#!/usr/bin/env bash
#displays the content of /etc/passwd

while  read -r
do
    echo "$REPLY" | awk -F: '{ printf("The user %s is part of the %d gang, lives in %s and rides %s. %d'\''s place is protected by the passcode x, more info about the user here: %s \n", $1, $3, $6, $7,$3,$1) }'
done < <(cat /etc/passwd)
