#!/usr/bin/env bash
#this script displays hours with its lingering minutes

i=0
while [ "$i" -lt 13 ]
    do
        echo "Hour: $i"
        j=1
        while [ "$j" -lt 60 ]
        do
            echo "$j"
            (( j++ ))
        done
    (( i++ ))
    done